# 44
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

from itertools import count


def pentagonal_numbers():
    for i in count(1):
        yield int((i * (3 * i - 1)) / 2)


pentagonal_num = list()
pentagonal_gen = pentagonal_numbers()
for i in pentagonal_gen:
    pentagonal_num.append(i)
    if i > 1_000:
        break
    print(i)
